### ISSUE TITLE
An empty plan, 1..0, causes parser error when it occurs right after another plan

### ISSUE THREAD

**Issue by japod** [tupilabs/tap4j#42]
Here is an excerpt from problematic TAP input:

```
# Subtest: test/exposed-harness.js
    # Subtest: main harness object is exposed
        ok 1 - tape.getHarness is a function
        ok 2 - should be equal
        1..2
    ok 1 - main harness object is exposed # time=15.769ms

    1..1
    # time=41.539ms

    1..0
    # tests 0
    # pass  0

    # ok

ok 13 - test/exposed-harness.js # time=264.253ms
```
The 1..0 plan above causes org.tap4j.parser.ParserException: Error parsing TAP Stream: Duplicated TAP Plan found

**Comment by kinow** [comment]
That is a very interesting case! Pulling PR locally to run the code, but the PR looks great!

**Comment by kinow** [comment]
Pull request merged. Thanks @japod !

**Comment by kinow** [comment]
@japod , pull request merged, I'll check all the dependencies to see if I can upgrade anything, and then I'll cut a new release.

You have contributed good code, and in parts of the code that few would dare to adventure and change. If you feel like doing more contributions, I would be happy to grant karma to your user to push changes directly.

I have reviewed your changes, but they were always in great shape, with tests, following the code standards and patterns (even if they were not always the best :-) )

So even if you are too busy or not interested, this invitation is always a way to thank you for your contribution.

Cheers
Bruno

**Comment by japod** [comment]
Hi Bruno,

Thank you very much for the quick response and also for the karma offer!

Although I can not be quite sure if there are going to be more contributions from my side,
i would be very flattered to get the permissions granted. We use tap4j to evaluate output
of our node.js/npm testing in Jenkins. As we cover more and more packages,
our testing process could bring up some additional use-cases in the future 
that might require tap4j updates. In such a case i would be happy to contribute
with appropriate features/patches.

Cheers,

~Jakub

**Comment by kinow** [comment]
Hi Jakub,

Not a problem. If you have the need to fix or change anything in the source code, at least now you can push the changes directly without having to wait for me. This way we don't run the risk of having stale pull requests, and changes get merged/solved faster.

And if you see any pull request that you believe could be merged, you can do that as well. Or if you still would like to change something via a pull request for review, always happy to help :-)

Welcome aboard, if you'd like to test your write permission, feel free to add your details to the project pom.xml under authors, and/or AUTHORS file.

Cheers
Bruno
