### ISSUE TITLE
Junit TapListener method list bug

### ISSUE THREAD

**Issue by benhyland** [tupilabs/tap4j#51]
https://github.com/tupilabs/tap4j/blob/ae93e64c0fe4c3dfd0800a2845b918160e73b682/tap4j-ext/src/main/java/org/tap4j/ext/junit/listener/TapListener.java#L126

It's probably a bug to try to compare Description and JUnitTestData?
Blame backwards compatibility of containers when generics arrived for this one :/

**Comment by kinow** [comment]
Oh, very likely! If you are able to work on a pull request for that, I'd be happy to review & merge :-)

**Comment by kinow** [comment]
Thanks for the pull requests @benhyland . I just cut a release which should include your change, 4.4. It should be out in a few minutes. The site failed to build/deploy, so I will try to update the plugin and regenerate later, but as there are no changes in the docs, it shouldn't be an issue.

**Comment by benhyland** [comment]
Thanks very much for the quick responses!

**Comment by kinow** [comment]
Not a problem. You did the whole work, reporting the ticket, fixing the issue, sending the pull request. That's the least I could do. :-)
