### ISSUE TITLE
tap4j.org has been hacked

### ISSUE THREAD

**Issue by beatngu13** [tupilabs/tap4j#58]
See screenshot… 😕

<img width="1680" alt="tap4j-org" src="https://user-images.githubusercontent.com/11643714/54547128-6d147700-49a5-11e9-8c92-e9be9a9ab909.png">

**Comment by kinow** [comment]
Hi,

I haven't renewed the domain, and will move artefacts under a github repository in maven.

That's just someone that bought the expired domain name.

Thanks
Bruno
